import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Configure local font
const nippo = localFont({
  src: '../fonts/Nippo-Regular.woff2', // Adjust path
  variable: '--font-nippo', // Optional: for CSS variable support
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${nippo.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${nippo.className}`}>{children}</body>
    </html>
  );
}
